
import pptxgen from "pptxgenjs"

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B"
}


export const generatePpt = async (data) => {
    const ppt = new pptxgen()
    ppt.layout = "LAYOUT_WIDE"
    ppt.author = "Syntrix AI"
    ppt.title = data.title
    ppt.subject = data.title
    ppt.company = "SyntrixAI"
    ppt.lang = "en-us"
    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
        lang: "en-us"
    }


    const addContentSlide = (ppt, title, points, page, total) => {
        const slide = ppt.addSlide()
        slide.background = {
            color: COLORS.white
        }

        slide.addText(title, {
            x: 0.6,
            y: 0.35,
            w: 10,
            h: 0.4,
            color: COLORS.primary,
            bold: true,
            fontSize: 24,
        })

        slide.addShape(ppt.ShapeType.line, {
            x: 0.6,
            y: 0.85,
            w: 12,
            h: 0,
            line: {
                color: COLORS.border,
                w: 1.2,
            }
        })

        const visiblePoints = points.slice(0, 6)

        visiblePoints?.forEach((point, index) => {
            const y = 1.2 + index * 0.75 
        });

    }


    addCover(ppt, data)

    data?.slides?.forEach((i, s) => {
        addContentSlide(
            ppt,
            s.title,
            s.points,
            i + 1,
            data.slides.length
        )
    });

    addThankYou(ppt)
    return ppt
}

const addCover = (ppt, data) => {
    const slide = ppt.addSlide()
    slide.background = {
        color: COLORS.primary
    }
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: "60A5FA"
        },
        line: {
            color: "60A5FA"
        }
    })
    slide.addText(data.title, {
        x: 0.7,
        y: 1.7,
        w: 12,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28,
    })

    slide.addText(data.subtitle, {
        x: 1,
        y: 2.8,
        w: 11.5,
        h: 0.4,
        align: "center",
        color: "DBEAFE",
        fontSize: 15,
    })
    slide.addText("Generated by SyntrixAI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE",
        fontSize: 10,
    })
}















